name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ "main" ]   # main branch वर commit/push झाला की pipeline चालेल
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Java (JDK 17)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Cache Maven dependencies (speed up build)
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 4. Build with Maven
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # 5. Run Tests
    - name: Run Tests
      run: mvn test

    # 6. Package JAR
    - name: Package Artifact
      run: mkdir -p build && cp target/*.jar build/

    # 7. Upload build artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: spring-boot-app
        path: build/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: spring-boot-app
        path: build

    # Example: Deploy to server (via SCP/SSH)
    - name: Deploy to Server
      run: |
        echo "Deploying Spring Boot app..."
        # Example: copy to server
        # scp -i private_key.pem build/*.jar user@your-server:/home/app/
        # ssh -i private_key.pem user@your-server "nohup java -jar /home/app/your-app.jar &"
