name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Cache Maven dependencies
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 4. Build with Maven (skip tests temporarily)
    - name: Build with Maven
      run: |
        mvn clean package -DskipTests
        if [ $? -ne 0 ]; then
          echo "Maven build failed!"
          exit 1
        fi

    # 5. Run Tests (optional)
    - name: Run Tests
      run: |
        mvn test || echo "Tests failed but continue"

    # 6. Package Artifact safely
    - name: Package Artifact
      run: |
        mkdir -p build
        JAR_FILE=$(ls target/*.jar 2>/dev/null | head -n 1)
        if [ -f "$JAR_FILE" ]; then
          cp "$JAR_FILE" build/
          echo "Jar copied to build folder: $JAR_FILE"
        else
          echo "No jar found, failing workflow"
          exit 1
        fi

    # 7. Upload Artifact (latest v4)
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-app
        path: build/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # 1. Download artifact
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: spring-boot-app
        path: build

    # 2. Deploy to Server (example)
    - name: Deploy to Server
      run: |
        echo "Deploying Spring Boot app..."
        # Uncomment below and configure your server secrets
        # echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        # chmod 600 private_key.pem
        # scp -i private_key.pem build/*.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/app/
        # ssh -i private_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "nohup java -jar /home/app/your-app.jar &"
